import { FuseNavigation } from "../../@fuse/types/fuse-navigation";
export const navigation: FuseNavigation[] = [
    {
        id: "accueil",
        title: "Accueil",
        //translate: 'NAV.SAMPLE.TITLE',
        type: "item",
        icon: "home",
        url: "/accueil",
    },

    //debut administrastion systeme
    {
        id: "admin",
        title: "Administration du système",
        //translate: 'NAV.SAMPLE.TITLE',
        type: "collapsable",
        icon: "security",

        children: [
            {
                id: "user",
                title: "Gestion Utilisateurs",
                //translate: 'NAV.SAMPLE.TITLE',
                type: "item",
                icon: "person",
                url: "administration/utilisateur",
            },
            {
                id: "ddb",
                title: "Données de Base",
                //translate: 'NAV.SAMPLE.TITLE',
                type: "collapsable",
                icon: "person",

                children: [
                    {
                        id: "composante",
                        title: "Composante",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/composante",
                    },
                    {
                        id: "decoupage",
                        title: "Découpage administratif",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/decoupage-administratif",
                    },
                    {
                        id: "type_activite",
                        title: "Type de l'activité, ARSE, ACT",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/type-activite-arse-act",
                    },
                    {
                        id: "agex",
                        title: "AGEX/AGEP/CPS",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/agex-agep-cps",
                    },
                    {
                        id: "resultat_plainte",
                        title: "Type/Résultat Plainte",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/type-resultat-plainte",
                    },
                    {
                        id: "question_menage",
                        title: "Questionnaire ménage",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/questionnaire-menage",
                    },
                    {
                        id: "question_individu",
                        title: "Questionnaire individu",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/questionnaire-individu",
                    },
                    {
                        id: "pac",
                        title: "Gérer PAC",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/gerer-pac",
                    },
                    {
                        id: "consultant",
                        title: "Consultant",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/consultant",
                    },
                    {
                        id: "milieu",
                        title: "Milieu/Vague/ZIP",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/milieu-vague-zip",
                    },
                    {
                        id: "plan",
                        title: "Plan action réinstallation",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/plan-action-reinstallation",
                    },
                    {
                        id: "phase",
                        title: "Phase execution et année",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/phase-execution-et-annee",
                    },
                    {
                        id: "lien_parente",
                        title: "Lien de parenté",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/lien-parente",
                    },
                    {
                        id: "formation_ml",
                        title: "Formation ML Outil de comm",
                        //translate: 'NAV.SAMPLE.TITLE',
                        type: "item",
                        icon: "person",
                        url: "donnees-de-base/formation",
                    },
                ],
            },
        ],
    },
    //fin administrastion systeme

    //debut ARSE=> ariep
    {
        id: "tms",
        title: "TMS",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "inscrit",
                title: "Ménage inscrit",
                type: "item",
                icon: "person",
                url: "/tms/menage-inscrit-tms",
            },
            {
                id: "selectionne",
                title: "Ménage préselectionné",
                type: "item",
                icon: "person",
                url: "/tmnc/menage-preselectionne-tmnc",
            },
            {
                id: "beneficiaire",
                title: "Ménage bénéficiaire",
                type: "item",
                icon: "person",
                url: "/tms/menage-beneficiaire-tms",
            },
            {
                id: "carte",
                title: "Carte bénéficiaire",
                type: "item",
                icon: "person",
                url: "/tmnc/carte-beneficiaire",
            },
            // {
            //     id: "memoire",
            //     title: "Gérer Mémoire descriptive du projet",
            //     type: "item",
            //     icon: "person",
            //     url: "/arse/gerer-mpd",
            // },
            {
                id: "agep",
                title: "Gérer AGEP",
                type: "item",
                icon: "person",
                url: "/tms/contrat_agep",
            },
        ],
    },
    //fin tms
    //debut ariep
    {
        id: "ariep",
        title: "ARIEP",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "inscrit",
                title: "Ménage Inscrit",
                type: "item",
                icon: "person",
                url: "/produit",
            },
            {
                id: "preselectionne",
                title: "Ménage présélectionné",
                type: "item",
                icon: "person",
                url: "/ariep/menage-preselectionne-ariep",
            },
            {
                id: "beneficiaire",
                title: "Menage bénéficiaire",
                type: "item",
                icon: "person",
                url: "/ariep/menage-beneficiaire-ariep",
            },
            {
                id: "carte",
                title: "Carte bénéficiaire",
                type: "item",
                icon: "person",
                url: "/ariep/carte-beneficiaire",
            },
            {
                id: "memoire",
                title: "Gérer Mémoire descriptive du projet",
                type: "item",
                icon: "person",
                url: "ariep/gerer-mpd",
            },
            {
                id: "agep",
                title: "Gérer AGEP",
                type: "item",
                icon: "person",
                url: "/ariep/contrat_agep",
            },
        ],
    },
    //fin ariep
    //debut actr
    {
        id: "actr",
        title: "ACTR",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "inscrit",
                title: "Ménage inscrit",
                type: "item",
                icon: "person",
                url: "/act/menage-inscrit-act",
            },
            {
                id: "selection",
                title: "Ménage préselectionné",
                type: "item",
                icon: "person",
                url: "/actr/menage-preselectionne-actr",
            },
            {
                id: "beneficiaire",
                title: "Ménage bénéficiaire",
                type: "item",
                icon: "person",
                url: "/actr/menage-beneficiaire-actr",
            },
            {
                id: "carte",
                title: "carte bénéficiaire",
                type: "item",
                icon: "person",
                url: "/actr/carte-beneficiaire",
            },
            {
                id: "fiche",
                title: "Fiche travailleur",
                type: "item",
                icon: "person",
                url: "/actr/fiche-travailleur",
            },
            {
                id: "memoire",
                title: "Gérer Mémoire descriptive du projet",
                type: "item",
                icon: "person",
                url: "/actr/gerer-mpd",
            },
            {
                id: "agep",
                title: "Gérer agep",
                type: "item",
                icon: "person",
                url: "/actr/contrat_agep",
            },
            {
                id: "pges",
                title: "Gérer PGES ACTR",
                type: "item",
                icon: "person",
                url: "/act/gerer_pges",
            },
        ],
    },
    //fin actr
    //debut IDB
    // {
    //     id: "idb",
    //     title: "IDB",
    //     type: "collapsable",
    //     icon: "home",
    //     children: [
    //         {
    //             id: "reference",
    //             title: "Données référentielles",
    //             type: "item",
    //             icon: "person",
    //             url: "/produit",
    //         },
    //         {
    //             id: "infrastrucure",
    //             title: "Infrastructure/IDB",
    //             type: "item",
    //             icon: "person",
    //             url: "/produit",
    //         },
    //         {
    //             id: "agep",
    //             title: "Gérer AGEP",
    //             type: "item",
    //             icon: "person",
    //             url: "/produit",
    //         },
    //         {
    //             id: "pges",
    //             title: "Gérer PGES IDB",
    //             type: "item",
    //             icon: "person",
    //             url: "/produit",
    //         },
    //     ],
    // },

    //fin IDB
    //debut Mesure d'accompagnement
    {
        id: "mesure",
        title: "Mesure d'accompagnement",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "act_mesure_accom",
                title: "TMS",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "sensi_act",
                        title: "Sensibilisation ménage",
                        type: "item",
                        icon: "person",
                        url: "macc/tms/sensibilisation-menage",
                    },
                ],
            },
            {
                id: "arse",
                title: "ARIEP",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "formaagex",
                        title: "Formation dex AGEX",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "theme",
                                title: "Thematique de Formation AGEX",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "suivi",
                                title: "Suivi de Formation AGEX",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                        ],
                    },
                    {
                        id: "leader",
                        title: "Mère leader",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "donnees",
                                title: "Données référentielles",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "mlpl",
                                title: "Groupe ML/PL",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "fiche",
                                title: "Fiche Supérvision Dir Rég",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "visite",
                                title: "Visite à domicile",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "rapport",
                                title: "Rapport mensuel",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                        ],
                    },
                    {
                        id: "formation",
                        title: "Formation mère leader",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "supervision",
                                title: "Supervision formation ML/CP",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "ml",
                                title: "Formation ML",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                        ],
                    },
                    {
                        id: "ebe",
                        title: "Sensibilisation EBE",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "supervision",
                                title: "Supervision formation EBE",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "planing",
                                title: "Planning EBE ARIEP",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                            {
                                id: "realisation",
                                title: "Réalisation EBE ARIEP",
                                type: "item",
                                icon: "home",
                                url: "/produit",
                            },
                        ],
                    },
                    {
                        id: "ong",
                        title: "Livrable ONG d'encadrement",
                        type: "item",
                        icon: "person",
                        url: "macc/ariep/livrable-ong-encadrement",
                    },
                    {
                      id: "sensibilisation",
                      title: "Sensibilisation ménage",
                      type: "item",
                      icon: "person",
                      url: "macc/ariep/sensibilisation-menage"
                  },
                ],
            },
            {
                id: "covid",
                title: "ACTR",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "sensi",
                        title: "Sensibilisation ménage",
                        type: "item",
                        icon: "person",
                        url: "macc/actr/sensibilisation-menage",
                    },
                ],
            },
        ],
    },

    //fin mesure d'accompagnement
    //debut suivi activite
    {
        id: "suivi",
        title: "Suivi activité",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "act",
                title: "TMS",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "receptrice",
                        title: "Fiches réceptrices",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "fiche1",
                                title: "Fiche réceptrice 1",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/tms/fiche-receptrice/premier-fiche-receptrice",
                            },
                            {
                                id: "fiche2",
                                title: "Fiche réceptrice 2",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/tms/fiche-receptrice/deuxieme-fiche-receptrice",
                            },
                            {
                                id: "fiche3",
                                title: "Fiche réceptrice 3",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/tms/fiche-receptrice/troisieme-fiche-receptrice",
                            },
                        ],
                    },
                    {
                        id: "paiements",
                        title: "Etats de paiements",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "paiement1",
                                title: "Premier paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/tms/etat-paiement/premier-paiement",
                            },
                            {
                                id: "paiement2",
                                title: "Deuxième paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/tms/etat-paiement/deuxieme-paiement",
                            },
                            {
                                id: "paiement3",
                                title: "Troisième paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/tms/etat-paiement/troisieme-paiement",
                            },
                        ],
                    },
                ],
            },
            {
                id: "arse",
                title: "ARIEP",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "receptrice",
                        title: "Fiches réceptrices",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "fiche1",
                                title: "Fiche réceptrice 1",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/fiche-receptrice/premier-fiche-receptrice",
                            },
                            {
                                id: "fiche2",
                                title: "Fiche réceptrice 2",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/fiche-receptrice/deuxieme-fiche-receptrice",
                            },
                            {
                                id: "fiche3",
                                title: "Fiche réceptrice 3",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/fiche-receptrice/troisieme-fiche-receptrice",
                            },
                            {
                                id: "fiche_soutien",
                                title: "Fiche fond de soutien",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/fiche-receptrice/quatrieme-fiche-receptrice",
                            },
                        ],
                    },
                    {
                        id: "paiements",
                        title: "Etats de paiements",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "paiement1",
                                title: "Premier paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/etat-paiement/premier-paiement",
                            },
                            {
                                id: "paiement2",
                                title: "Deuxième paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/etat-paiement/deuxieme-paiement",
                            },
                            {
                                id: "paiement3",
                                title: "Troisième paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/etat-paiement/troisieme-paiement",
                            },
                            {
                                id: "fond_soutien",
                                title: "Fond de soutien",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/ariep/etat-paiement/quatrieme-paiement",
                            },
                        ],
                    },
                    {
                        id: "Profilage_orientation",
                        title: "Profilage orientation",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "fiche_profilage_orientation",
                                title: "Fiche profilage orientation",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                        ],
                    },
                    {
                        id: "activites_menages",
                        title: "Activités ménages",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "formation_technique_base",
                        title: "Formation technique de base",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "formation_menage",
                                title: "Formation des ménages",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                            {
                                id: "thematique_formation_agex",
                                title: "Thematique de Formation AGEX",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                            {
                                id: "suivi_formation_agex",
                                title: "Suivi de Formation Agex",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                        ],
                    },
                    {
                        id: "theme_formation",
                        title: "Thème-Formation",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "suivi_technique",
                        title: "Suivi technique",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "fiche_plan_relevement",
                                title: "Fiche plan de relèvement",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                            {
                                id: "suivi_plan_relevement",
                                title: "Suivi Fiche plan de relèvement",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                        ],
                    },
                    {
                        id: "suivi_evaluation",
                        title: "Suivi et évaluation",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "questionnaire_ml",
                                title: "Questionnaire ML",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                            {
                                id: "information_ml",
                                title: "Information ML",
                                type: "item",
                                icon: "person",
                                url: "/produit",
                            },
                        ],
                    },
                ],
            },

            {
                id: "actr",
                title: "ACTR",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "paiement1",
                        title: "Premier paiement",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "fiche_etat_presence",
                                title: "Fiche/Etat de presence",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/premier-paiement/export-fiche-de-presence",
                            },
                            {
                                id: "enregistrer_presence",
                                title: "Enregistrer Etat de presence",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/premier-paiement/enregistrer-etat-de-presence",
                            },
                            {
                                id: "fiche_etat_paiement",
                                title: "Fiche/Etat de paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/premier-paiement/export-fiche-etat-de-paiement",
                            },
                            {
                                id: "enregistrer_paiement",
                                title: "Enregistrer Etat de paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/premier-paiement/enregistrer-etat-de-paiement",
                            },
                        ],
                    },
                    {
                        id: "paiement2",
                        title: "Deuxieme paiement",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "fiche_etat_presence",
                                title: "Fiche/Etat de presence",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/deuxieme-paiement/export-fiche-de-presence",
                            },
                            {
                                id: "enregistrer_presence",
                                title: "Enregistrer Etat de presence",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/deuxieme-paiement/enregistrer-etat-de-presence",
                            },
                            {
                                id: "fiche_etat_paiement",
                                title: "Fiche/Etat de paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/deuxieme-paiement/export-fiche-etat-de-paiement",
                            },
                            {
                                id: "enregistrer_paiement",
                                title: "Enregistrer Etat de paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/deuxieme-paiement/enregistrer-etat-de-paiement",
                            },
                        ],
                    },
                    {
                        id: "paiement3",
                        title: "Toisieme paiement",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "fiche_etat_presence",
                                title: "Fiche/Etat de presence",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/troisieme-paiement/export-fiche-de-presence",
                            },
                            {
                                id: "enregistrer_presence",
                                title: "Enregistrer Etat de presence",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/troisieme-paiement/enregistrer-etat-de-presence",
                            },
                            {
                                id: "fiche_etat_paiement",
                                title: "Fiche/Etat de paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/troisieme-paiement/export-fiche-etat-de-paiement",
                            },
                            {
                                id: "enregistrer_paiement",
                                title: "Enregistrer Etat de paiement",
                                type: "item",
                                icon: "person",
                                url: "/suivi-activite/actr/troisieme-paiement/enregistrer-etat-de-paiement",
                            },
                        ],
                    },
                ],
            },
            // {
            //     id: "idb",
            //     title: "IDB",
            //     type: "collapsable",
            //     icon: "person",
            //     children: [
            //         {
            //             id: "etudes_techniques",
            //             title: "Etudes techniques",
            //             type: "item",
            //             icon: "person",
            //             url: "/produit",
            //         },
            //         {
            //             id: "dossiers_techniques_projet",
            //             title: "Dossiers techniques projet",
            //             type: "item",
            //             icon: "person",
            //             url: "/produit",
            //         },
            //         {
            //             id: "pges",
            //             title: "P.G.E.S",
            //             type: "item",
            //             icon: "person",
            //             url: "/produit",
            //         },
            //         {
            //             id: "execution_travaux",
            //             title: "Exécution travaux",
            //             type: "item",
            //             icon: "person",
            //             url: "/produit",
            //         },
            //         {
            //             id: "avancement_travaux",
            //             title: "Avancement travaux",
            //             type: "item",
            //             icon: "person",
            //             url: "/produit",
            //         },
            //         {
            //             id: "reception_provisoire",
            //             title: "Reception provisoire",
            //             type: "item",
            //             icon: "person",
            //             url: "/produit",
            //         },
            //         {
            //             id: "Reception_definitive",
            //             title: "Reception définitive",
            //             type: "item",
            //             icon: "person",
            //             url: "/produit",
            //         },
            //     ],
            // },
        ],
    },
    //fin mesure d'accompagnement
    //debut gerer agex
    {
        id: "agex",
        title: "Gérer AGEX",
        type: "item",
        icon: "home",
        url: "/agex",
    },
    //plaintes
    {
        id: "plaintes",
        title: "Plaintes",
        type: "item",
        icon: "home",
        url: "/plainte",
    },
    //importation
    {
        id: "importation",
        title: "Importation",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "importation_fiche_profilage",
                title: "Fiche profilage",
                type: "item",
                icon: "home",
                url: "/importation/fiche-profilage",
            },
            {
                id: "importation_plan_resilience",
                title: "Plan de resilience",
                type: "item",
                icon: "home",
                url: "/importation/plan-de-resilience",
            },
            {
                id: "importation_menage",
                title: "Ménage",
                type: "collapsable",
                icon: "home",
                children: [
                    {
                        id: "imporation_menage_inscription_menage",
                        title: "Inscription ménage",
                        type: "item",
                        icon: "person",
                        url: "/importation/menage/inscription-menage",
                    },
                    {
                        id: "importation_maj_recepteur",
                        title: "MAJ Info Recepteur",
                        type: "item",
                        icon: "person",
                        url: "/importation/menage/info-recepteur",
                    },
                    {
                        id: "importation_maj_beneficiaire",
                        title: "MAJ Beneficiaire",
                        type: "item",
                        icon: "person",
                        url: "/importation/menage/maj-beneficiaire",
                    },
                ],
            },
            {
                id: "importation_etat_presence",
                title: "Etat de presence",
                type: "collapsable",
                icon: "home",
                children: [
                    {
                        id: "importation_etat_presence_cycle1",
                        title: "Cycle 1",
                        type: "collapsable",
                        icon: "home",
                        children: [
                            {
                                id: "importation_etat_presence1_cycle1",
                                title: "Etat de presence 1/Cycle1",
                                type: "item",
                                icon: "person",
                                url: "/importation/etat-presence/cycle1/etat-presence1",
                            },
                            {
                                id: "importation_etat_presence2_cycle1",
                                title: "Etat de presence 2/Cycle1",
                                type: "item",
                                icon: "person",
                                url: "/importation/etat-presence/cycle1/etat-presence2",
                            },
                        ],
                    },
                    {
                        id: "importation_etat_presence_cycle1",
                        title: "Cycle 2",
                        type: "collapsable",
                        icon: "home",
                        children: [
                            {
                                id: "importation_etat_presence1_cycle2",
                                title: "Etat de presence 1/Cycle2",
                                type: "item",
                                icon: "person",
                                url: "/importation/etat-presence/cycle2/etat-presence1",
                            },
                            {
                                id: "importation_etat_presence2_cycle2",
                                title: "Etat de presence 2/Cycle2",
                                type: "item",
                                icon: "person",
                                url: "/importation/etat-presence/cycle2/etat-presence2",
                            },
                        ],
                    },
                    {
                        id: "imporation_etat_presence3_fond_sortie",
                        title: "Etat presence3/Fond sortie",
                        type: "item",
                        icon: "person",
                        url: "/importation/etat-presence/etat-présence-3",
                    },
                ],
            },
            {
                id: "importation_paiement",
                title: "Paiement",
                type: "collapsable",
                icon: "home",
                children: [
                    {
                        id: "importation_paiement_tms",
                        title: "TMS",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "importation_paiement_tms-paiement1",
                                title: "Premier paiement",
                                type: "item",
                                icon: "person",
                                url: "/importation/paiement/tms/premier-paiement",
                            },
                            {
                                id: "importation_paiement_tms_paiement2",
                                title: "Deuxieme paiement",
                                type: "item",
                                icon: "person",
                                url: "/importation/paiement/tms/deuxieme-paiement",
                            },
                            {
                                id: "importation_paiement_tms_paiement3",
                                title: "Troisieme paiement",
                                type: "item",
                                icon: "person",
                                url: "/importation/paiement/tms/troisieme-paiement",
                            },
                        ],
                    },
                    {
                        id: "importation_paiement_ariep",
                        title: "ARIEP",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "importation_paiement_ariep_paiement1",
                                title: "Premier paiement",
                                type: "item",
                                icon: "person",
                                url: "/importation/paiement/ariep/premier-paiement",
                            },
                            {
                                id: "importation_paiement_ariep_paiement2",
                                title: "Deuxieme paiement",
                                type: "item",
                                icon: "person",
                                url: "/importation/paiement/ariep/deuxieme-paiement",
                            },
                            {
                                id: "importation_paiement_ariep_paiement3",
                                title: "Troisieme paiement",
                                type: "item",
                                icon: "person",
                                url: "/importation/paiement/ariep/troisieme-paiement",
                            },
                            {
                                id: "importation_paiement_ariep_fond_sortie",
                                title: "Fond de sortie",
                                type: "item",
                                icon: "person",
                                url: "/importation/paiement/ariep/quatrieme-paiement",
                            },
                        ],
                    },
                    {
                        id: "importation_paiement_actr",
                        title: "ACTR",
                        type: "collapsable",
                        icon: "person",
                        children: [
                            {
                                id: "importation_paiement_actr_cycle1",
                                title: "Cycle 1",
                                type: "collapsable",
                                icon: "home",
                                children: [
                                    {
                                        id: "importation_paiement_actr_cycle1_paiement1_cycle1",
                                        title: "Paiement 1/Cycle1",
                                        type: "item",
                                        icon: "person",
                                        url: "/importation/paiement/actr/cycle1/premier-paiement",
                                    },
                                    {
                                        id: "importation_paiement_actr_cycle1_paiement2_cycle2",
                                        title: "Paiement 2/Cycle1",
                                        type: "item",
                                        icon: "person",
                                        url: "/importation/paiement/actr/cycle1/deuxieme-paiement",
                                    },
                                ],
                            },
                            {
                                id: "importation_paiement_actr_cycle1",
                                title: "Cycle 2",
                                type: "collapsable",
                                icon: "home",
                                children: [
                                    {
                                        id: "importation_paiement_actr_cycle2_paiement1_cycle1",
                                        title: "Paiement 1/Cycle2",
                                        type: "item",
                                        icon: "person",
                                        url: "/importation/paiement/actr/cycle2/premier-paiement",
                                    },
                                    {
                                        id: "importation_paiement_actr_cycle2_paiement2_cycle2",
                                        title: "Paiement 2/Cycle2",
                                        type: "item",
                                        icon: "person",
                                        url: "/importation/paiement/actr/cycle2/deuxieme-paiement",
                                    },
                                ],
                            },
                            {
                                id: "importation_paiement_actr_fond_sortie",
                                title: "Fond sortie",
                                type: "item",
                                icon: "person",
                                url: "/importation/actr/fond-de-sortie",
                            },
                        ],
                    },
                ],
            },
        ],
    },

    //debut Tableau de bord
    {
        id: "bord",
        title: "Tableau de bord",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "indicateur",
                title: "Indicateur",
                type: "item",
                icon: "person",
                url: "tableau-de-bord/indicateur",
            },
            {
                id: "arse",
                title: "ARIEP",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "objectif_arse",
                        title: "Objectif",
                        type: "item",
                        icon: "person",
                        url: "ariep/objectif",
                    },
                    {
                        id: "tableau_de_bord_arse",
                        title: "Tableau de bord",
                        type: "item",
                        icon: "person",
                        url: "ariep/tableau-de-bord",
                    },
                ],
            },
            {
                id: "act",
                title: "ACTR",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "objectif_act",
                        title: "Objectif",
                        type: "item",
                        icon: "person",
                        url: "actr/objectif",
                    },
                    {
                        id: "tableau_de_bord_act",
                        title: "Tableau de bord",
                        type: "item",
                        icon: "person",
                        url: "actr/tableau-de-bord",
                    },
                ],
            },
            {
                id: "mesure_accompagnement",
                title: "Mesure d/'accompagnement",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "objectif_accompagnement",
                        title: "Objectif",
                        type: "item",
                        icon: "person",
                        url: "macc/objectif",
                    },
                    {
                        id: "tableau_de_bord_accompagnement",
                        title: "Tableau de bord",
                        type: "item",
                        icon: "person",
                        url: "macc/tableau-de-bord",
                    },
                ],
            },
        ],
    },

    //fin tableau de bord

    //suivi budgetaire
    {
        id: "budget",
        title: "Suivi budgétaire",
        type: "item",
        icon: "home",
        url: "/client",
    },

    //debut suivi evaluation
    {
        id: "evaluation",
        title: "Suivi évaluation",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "arse",
                title: "ARIEP",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "vague_1_arse",
                        title: "Vague 1",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "vague_2_arse",
                        title: "Vague 2",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "vague_3_arse",
                        title: "Vague 3",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                ],
            },
            {
                id: "act",
                title: "ACTR",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "vague_1_act",
                        title: "Vague 1",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "vague_2_act",
                        title: "Vague 2",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "vague_3_act",
                        title: "Vague 3",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                ],
            },
            {
                id: "macc",
                title: "MACC",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "vague_1_macc",
                        title: "Vague 1",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "vague_2_macc",
                        title: "Vague 2",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "vague_3_macc",
                        title: "Vague 3",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                ],
            },
            {
                id: "planning",
                title: "Planning",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "planning",
                        title: "DDB Planning",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "planning_general",
                        title: "Planning général",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                ],
            },
        ],
    },

    //fin suivi evaluation

    //Reporting
    {
        id: "reporting",
        title: "Reporting",
        type: "collapsable",
        icon: "home",
        children: [
            {
                id: "menage",
                title: "Ménages",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "menage_beneficiaire",
                        title: "Ménage bénéficiaire",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "beneficiaire_activite_sexe",
                        title: "Bénéficiaire par Activité/Sexe",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "liste_menage_inscrit",
                        title: "Liste ménage inscrit",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "liste_menage_preselectionne",
                        title: "Liste ménage préseléctionné",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "liste_menage_beneficiaire",
                        title: "Liste ménage bénéficiaire",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "liste_menage_sorti",
                        title: "Liste ménage sorti",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "liste_menage_inapte",
                        title: "Liste ménage inapte",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                ],
            },
            {
                id: "macc",
                title: "MACC",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "thematique_formation_arse",
                        title: "Thématique formation ARIEP",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "thematique_sensibilisation",
                        title: "Thématique sensibilisation MACC",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "nombre_groupe_mlpl",
                        title: "Nombre groupe ML/PL",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                ],
            },
            {
                id: "idb",
                title: "I.D.B",
                type: "collapsable",
                icon: "person",
                children: [
                    {
                        id: "infrastructure",
                        title: "Infrastructure",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                    {
                        id: "entreprise_et_bureau",
                        title: "Entreprise et Bureau d'étude",
                        type: "item",
                        icon: "person",
                        url: "/produit",
                    },
                ],
            },
        ],
    },
];
